/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tiengviet2vn_dict_3;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull("Main is blank!", classUnderTest.getGreeting());
    }
}
